### ISSUE TITLE
Közösség felület elosztó

### ISSUE THREAD

**Issue by molnaraadam** [molnaredom/asztro#160]
# Széttagolt közösségi fülek frontenden 

### chatek
- [ ] chat eloszto
- [x] chat 1-1
- [ ] chat csoportok
- [ ] chat iranyzaton beluli

### hirek
- [x] hirportal
- [ ] vicces memek
- [ ] bejelentesek

### egyeb
- [ ] Analogia viták

**Comment by molnaredom** [comment]
Nincs ennyi funkcio de ami van az szep
